# -*- coding: utf-8 -*-
"""SCT_ML_Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gs-QXNrCCQbn2e8MziLDhX399lCoAqjC
"""

# Elbow Method to find optimal clusters
wcss = []
max_clusters = len(df)  # can't have more clusters than data points

for i in range(1, max_clusters + 1):
    kmeans = KMeans(n_clusters=i, random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

plt.plot(range(1, max_clusters + 1), wcss, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.show()